# Generated by Django 5.1.6 on 2025-02-06 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presentaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpresentaciones',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='modelpresentaciones',
            name='integrantes',
            field=models.ManyToManyField(blank=True, null=True, related_name='integrantes', to='presentaciones.modelintegrantes', verbose_name='Integrantes'),
        ),
    ]
