# Generated by Django 5.1.6 on 2025-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpostulante',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='modelpostulante',
            name='telefono',
            field=models.CharField(max_length=10, verbose_name='Teléfono'),
        ),
    ]
