# Generated by Django 5.1.6 on 2025-02-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelIntegrantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre(s) del integrante')),
                ('apellidos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellidos del integrante')),
                ('dieta', models.CharField(blank=True, default='Sin especificación', max_length=100, null=True, verbose_name='Especificacion de dieta')),
            ],
            options={
                'verbose_name': 'Integrante',
                'verbose_name_plural': 'Integrantes',
                'db_table': 'integrantes',
            },
        ),
        migrations.CreateModel(
            name='ModelPresentaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.DateField(blank=True, null=True, verbose_name='Fecha temporal')),
                ('nombre_agrupacion', models.CharField(max_length=100, verbose_name='Nombre de la agrupacion')),
                ('presentacion_grupo', models.CharField(max_length=200, verbose_name='Semblanza del grupo')),
                ('integrantes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='presentaciones.modelintegrantes', verbose_name='Integrantes')),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
                'db_table': 'presentaciones',
            },
        ),
    ]
