[project]
name = "backend"
version = "0.1.0"
description = "Backend service for the application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.25",
    "django>=5.2.6",
    "django-filter>=25.1",
    "djangorestframework>=3.16.1",
    "markdown>=3.9",
]
