# Generated by Django 5.1.6 on 2025-02-11 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGeneroEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre del evento')),
                ('descricion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Breve descripción del evento')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion del evento')),
                ('fecha_modificacion', models.DateField(auto_now_add=True, verbose_name='Fecha de modificacion del evento')),
                ('usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificacion')),
            ],
            options={
                'verbose_name': 'Genero presentaciones',
                'db_table': 'generos',
            },
        ),
    ]
