services:
  # Servicio de base de datos MySQL:
  database:
    image: mysql:8.0.41-bookworm
    environment:
      MYSQL_ROOT_PASSWORD: edqnLMCSf31.
      MYSQL_DATABASE: cauz
      MYSQL_USER: developer
      MYSQL_PASSWORD: anypassword
    ports:
      - "4002:3306"
    volumes:
      - db-cauz:/var/lib/mysql
    networks:
      - net-cauz
    restart: always
  # Servicio de Flask:
  flask:
    build:
      context: ../flask/
      dockerfile: Dockerfile
    volumes: # Hacer refencia a la carpeta flask (Donde ese esta programando el proyecto)
      - ../flask/:/app
    ports:
      - "4001:4001"
    networks:
      - net-cauz
    restart: always
  # Servicio de backend: (django)
  backend:
    build:
      context: ../django/
      dockerfile: Dockerfile
    command: bash -c "sleep 60 && python manage.py migrate && python manage.py runserver 0.0.0.0:4000"
    volumes: # Hacer refencia a la carpeta backend (Donde ese esta programando el proyecto)
      - ../django/:/app
    ports:
      - "4000:4000"
    networks:
      - net-cauz
    depends_on:
      - database
      - flask
    restart: always
  astro:
    build:
      context: ../astro/
      dockerfile: Dockerfile
    volumes: # Hacer refencia a la carpeta astro (Donde ese esta programando el proyecto)
      - ../astro/:/app
      - node_modules:/app/node_modules
    ports:
      - "4003:4003"
    networks:
      - net-cauz
    restart: unless-stopped
    depends_on:
      - backend
      - flask
    command: bash -c "sleep 10 && npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db-cauz:
  node_modules:
networks:
  # Red de tipo bridge
  net-cauz:
    driver: bridge
