# Generated by Django 5.1.6 on 2025-02-07 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postulantes', '0002_alter_modelpostulante_correo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSolicitudEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('nombre_evento', models.CharField(max_length=100, verbose_name='Nombre del evento')),
                ('genero', models.CharField(blank=True, max_length=100, null=True, verbose_name='Género')),
                ('fecha_tentativa', models.DateField(verbose_name='Fecha tentativa')),
                ('integrantes', models.CharField(max_length=150, verbose_name='Nombre de los integrantes')),
                ('meterial', models.CharField(max_length=500, verbose_name='Material')),
                ('postulante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='postulantes.modelpostulante', verbose_name='Postulante')),
            ],
            options={
                'verbose_name': 'Solicitud de evento',
                'verbose_name_plural': 'Solicitudes de eventos',
                'db_table': 'solicitud_eventos',
                'ordering': ['fecha_solicitud'],
            },
        ),
    ]
