# Generated by Django 5.1.6 on 2025-02-11 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero_presentacion', '0001_initial'),
        ('solicitud_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsolicitudeventos',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='genero_presentacion.modelgeneroeventos', verbose_name='Genero'),
        ),
    ]
