# Generated by Django 5.1.6 on 2025-02-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsolicitudeventos',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Aceptado'),
        ),
    ]
